import { useEffect, useState } from "react";
import { ArrowLeft, BookOpen, CheckCircle2, Clock3, Database, FileText, GitBranch, Layers3, PlayCircle } from "lucide-react";

import { getKnowledgeBaseV3, getKnowledgeLibraryV3 } from "@/api/client";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import DiagnosticPackagesPanel from "@/pages/knowledge-base/DiagnosticPackagesPanel";

const DETAIL_TABS = ["Overview", "Rules / Concepts", "Versions & Changes", "Dependencies", "Usage & History"];
const label = (value) => String(value || "").replaceAll("_", " ");

function LibraryCard({ item, onOpen }) {
  return <button type="button" onClick={() => onOpen(item.knowledge_base_id)} className="group rounded-lg border border-slate-200 bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-dq-purple/40 hover:shadow-md">
    <div className="flex items-start justify-between gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-dq-purple/10 text-dq-purple"><BookOpen className="h-5 w-5" /></span><span className="flex flex-wrap justify-end gap-1"><Badge variant="success">{label(item.lifecycle_state)}</Badge>{item.management_mode === "source_managed" && <Badge variant="outline">Source-managed</Badge>}</span></div>
    <h2 className="mt-4 font-semibold text-slate-950 group-hover:text-dq-purple">{item.name}</h2>
    <p className="mt-1 min-h-10 text-xs leading-5 text-slate-600">{item.purpose}</p>
    <div className="mt-4 border-t border-slate-100 pt-3"><div className="flex flex-wrap gap-1">{item.consumers.map((consumer) => <Badge key={consumer.id} variant="secondary">{consumer.id}</Badge>)}</div><div className="mt-3 flex items-center justify-between text-xs text-slate-500"><span>Active v{item.active_version || "—"}</span><span>{item.version_count} version{item.version_count === 1 ? "" : "s"}</span></div></div>
  </button>;
}

function WorkInProgress({ enhancements }) {
  return <section className="rounded-lg border border-dashed border-slate-300 bg-white/70 p-5"><div className="flex items-start gap-3"><Clock3 className="mt-0.5 h-5 w-5 text-amber-600" /><div><h2 className="font-semibold text-slate-900">Upcoming enhancements</h2><p className="mt-1 text-xs text-slate-500">Work in progress is separate from active, executable knowledge.</p></div></div><div className="mt-4 grid gap-3 lg:grid-cols-3">{enhancements.map((item) => <article key={item.enhancement_id} className="rounded-md border border-slate-200 bg-slate-50 p-4"><div className="flex items-start justify-between gap-2"><h3 className="text-sm font-semibold text-slate-800">{item.name}</h3><Badge variant="outline">{label(item.status)}</Badge></div><p className="mt-2 text-xs leading-5 text-slate-600">{item.description}</p>{item.items.length > 0 && <p className="mt-2 text-[11px] text-slate-500">Registered integrations: {item.items.map((entry) => entry.id).join(", ")}</p>}</article>)}</div></section>;
}

function Overview({ item }) {
  return <div className="space-y-4">
    <div className="grid gap-4 lg:grid-cols-[1.35fr_1fr]">
      <section className="rounded-lg border border-slate-200 bg-white p-5"><span className="text-xs font-semibold uppercase tracking-wide text-dq-purple">Objective</span><h3 className="mt-2 text-lg font-semibold text-slate-950">{item.objective}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{item.purpose}</p><dl className="mt-4 grid gap-3 border-t border-slate-100 pt-4 text-xs sm:grid-cols-2"><div><dt className="font-semibold text-slate-500">Governed content</dt><dd className="mt-1 text-slate-800">{item.content_label}</dd></div><div><dt className="font-semibold text-slate-500">Management</dt><dd className="mt-1 text-slate-800">{item.management_mode === "library_managed" ? "Managed in the Library" : "Source-managed during transition"}</dd></div></dl></section>
      <section className="rounded-lg border border-slate-200 bg-white p-5"><h3 className="text-sm font-semibold text-slate-900">Consumers and stages</h3><div className="mt-3 space-y-2">{item.consumers.map((consumer) => <div key={consumer.id} className="flex items-center gap-2 rounded-md bg-slate-50 p-3 text-sm"><Badge>{consumer.id}</Badge><span>{consumer.name}</span></div>)}</div><div className="mt-4 flex flex-wrap gap-1">{item.consumption_stages.map((stage) => <Badge key={stage} variant="outline">{stage}</Badge>)}</div></section>
    </div>
    <section className="rounded-lg border border-slate-200 bg-white p-5"><h3 className="text-sm font-semibold text-slate-900">How the diagnostic works</h3><div className="mt-4 grid gap-2 md:grid-cols-5">{item.flow.map((step, index) => <div key={step} className="relative rounded-md border border-slate-200 bg-slate-50 p-3"><span className="text-[10px] font-bold text-dq-purple">STEP {index + 1}</span><p className="mt-1 text-xs font-medium leading-5 text-slate-700">{step}</p>{index < item.flow.length - 1 && <span className="absolute -right-2.5 top-1/2 z-10 hidden h-5 w-5 -translate-y-1/2 items-center justify-center rounded-full bg-dq-purple text-xs text-white md:flex">›</span>}</div>)}</div></section>
    <section className="rounded-lg border border-dq-purple/20 bg-gradient-to-r from-dq-purple/5 to-blue-50 p-5"><div className="flex items-start gap-3"><PlayCircle className="mt-0.5 h-5 w-5 text-dq-purple" /><div><span className="text-xs font-semibold uppercase tracking-wide text-dq-purple">Worked example</span><h3 className="mt-1 font-semibold text-slate-950">{item.example.title}</h3></div></div><div className="mt-4 grid gap-3 md:grid-cols-3"><div className="rounded-md bg-white/80 p-3"><div className="text-[10px] font-semibold uppercase text-slate-500">Inputs</div>{item.example.inputs.map((value) => <p key={value} className="mt-1 text-xs text-slate-700">• {value}</p>)}</div><div className="rounded-md bg-white/80 p-3"><div className="text-[10px] font-semibold uppercase text-slate-500">Diagnostic calculation</div><p className="mt-2 text-sm font-medium text-slate-800">{item.example.calculation}</p></div><div className="rounded-md bg-white/80 p-3"><div className="text-[10px] font-semibold uppercase text-slate-500">Outcome</div><p className="mt-2 text-xs leading-5 text-slate-700">{item.example.outcome}</p></div></div></section>
  </div>;
}

function RulesConcepts({ item }) {
  return <div className="space-y-4">
    <div className="grid gap-4 xl:grid-cols-3">
      <section className="rounded-lg border border-slate-200 bg-white p-5"><Database className="h-5 w-5 text-dq-purple" /><h3 className="mt-2 font-semibold text-slate-900">Inputs needed</h3><div className="mt-3 space-y-3">{item.inputs.map((input) => <div key={input.name} className="border-t border-slate-100 pt-3 first:border-0 first:pt-0"><div className="flex items-start justify-between gap-2"><span className="text-sm font-medium text-slate-800">{input.name}</span><Badge variant="outline">{input.requirement}</Badge></div><p className="mt-1 text-xs text-slate-500">From {input.source}</p></div>)}</div></section>
      <section className="rounded-lg border border-slate-200 bg-white p-5"><Layers3 className="h-5 w-5 text-dq-purple" /><h3 className="mt-2 font-semibold text-slate-900">Roles and context</h3><div className="mt-3 space-y-3">{item.roles.map((role) => <div key={role.name} className="rounded-md bg-slate-50 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><code className="text-xs font-semibold text-slate-800">{role.name}</code><Badge variant="secondary">{role.requirement}</Badge></div><p className="mt-1 text-xs leading-5 text-slate-600">{role.meaning}</p></div>)}</div></section>
      <section className="rounded-lg border border-slate-200 bg-white p-5"><GitBranch className="h-5 w-5 text-dq-purple" /><h3 className="mt-2 font-semibold text-slate-900">Dataset Structure Context (DSC)</h3><div className="mt-3 space-y-3">{item.dsc_requirements.map((row) => <div key={row.facet} className="border-t border-slate-100 pt-3 first:border-0 first:pt-0"><div className="flex flex-wrap items-center justify-between gap-2"><span className="text-sm font-medium text-slate-800">{row.facet}</span><Badge variant="outline">{row.requirement}</Badge></div><p className="mt-1 text-xs leading-5 text-slate-600">{row.use}</p></div>)}</div></section>
    </div>
    <section><div className="mb-3"><h3 className="font-semibold text-slate-900">Rules generated and executed</h3><p className="mt-1 text-xs text-slate-500">The run manifest creates executable instances only when the listed roles and prerequisites are satisfied.</p></div><div className="grid gap-3 lg:grid-cols-2">{item.rules.map((rule) => <article key={rule.id} className="rounded-lg border border-slate-200 bg-white p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><code className="text-xs font-semibold text-dq-purple">{rule.id}</code><h4 className="mt-1 text-sm font-semibold text-slate-900">{rule.name}</h4></div>{rule.expected_direction && <Badge>{label(rule.expected_direction)}</Badge>}</div><p className="mt-2 text-xs leading-5 text-slate-600">{rule.description}</p><div className="mt-3 flex flex-wrap gap-1">{rule.required_roles.map((role) => <Badge key={role} variant="secondary">Role: {role}</Badge>)}{(rule.prerequisites || []).map((value) => <Badge key={value} variant="outline">Declaration: {value}</Badge>)}</div><div className="mt-3 flex items-start gap-2 rounded-md bg-slate-50 p-2 text-xs text-slate-600"><CheckCircle2 className="mt-0.5 h-3.5 w-3.5 shrink-0 text-emerald-600" /><span>{rule.execution_state}</span></div></article>)}</div></section>
  </div>;
}

function Versions({ item }) {
  if (item.knowledge_base_id === "kbdoc_t2d6_row_completeness") return <DiagnosticPackagesPanel />;
  return <section className="overflow-hidden rounded-lg border border-slate-200 bg-white">{item.versions.map((version) => <div key={version.version_id} className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 px-4 py-3 first:border-t-0"><div><div className="flex items-center gap-2"><strong className="text-sm text-slate-800">v{version.version_label}</strong><Badge variant={version.lifecycle_state === "active" ? "success" : "secondary"}>{label(version.lifecycle_state)}</Badge></div><p className="mt-1 text-xs text-slate-500">{version.original_filename}</p></div><span className="text-xs text-slate-400">{version.created_at}</span></div>)}</section>;
}

function UsageHistory({ item }) {
  return <section className="rounded-lg border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5"><h3 className="font-semibold text-slate-900">Run-manifest usage</h3><p className="mt-1 text-xs text-slate-500">New manifests carry exact pins; older associations are labelled as legacy matches.</p></div>{item.usage_history.length ? <div className="divide-y divide-slate-100">{item.usage_history.map((run) => <div key={run.run_id} className="grid gap-3 p-4 md:grid-cols-[1.4fr_.7fr_.7fr_1fr]"><div><div className="text-sm font-medium text-slate-800">{run.item_name}</div><code className="mt-1 block text-[11px] text-slate-500">{run.run_id}</code></div><div><div className="text-[10px] font-semibold uppercase text-slate-400">Consumer</div><div className="mt-1 text-xs text-slate-700">D{run.diagnostic_id} · v{run.version_label || "unknown"}</div></div><div><div className="text-[10px] font-semibold uppercase text-slate-400">Run state</div><Badge className="mt-1" variant={run.status === "done" ? "success" : "outline"}>{label(run.status)}</Badge></div><div><div className="text-[10px] font-semibold uppercase text-slate-400">Provenance</div><div className="mt-1 flex flex-wrap gap-1"><Badge variant={run.reference_type === "pinned" ? "success" : "warning"}>{label(run.reference_type)}</Badge><Badge variant="outline">DSC: {label(run.dsc_state)}</Badge></div><p className="mt-1 text-[11px] text-slate-400">{run.finished_at || run.started_at || run.created_at}</p></div></div>)}</div> : <div className="p-8 text-center text-sm text-slate-500">No diagnostic manifests have referenced this KB yet.</div>}</section>;
}

function Detail({ knowledgeBaseId, onBack, onOpenSource }) {
  const [item, setItem] = useState(null); const [tab, setTab] = useState("Overview"); const [error, setError] = useState("");
  useEffect(() => { getKnowledgeBaseV3(knowledgeBaseId).then(setItem).catch((reason) => setError(reason.message)); }, [knowledgeBaseId]);
  if (error) return <div className="rounded-md border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>;
  if (!item) return <div className="rounded-md border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500">Loading knowledge base…</div>;
  return <div><Button variant="ghost" size="sm" onClick={onBack}><ArrowLeft className="h-4 w-4" /> Back to library</Button><div className="mt-3 flex flex-wrap items-start justify-between gap-4 rounded-lg border border-slate-200 bg-white p-5"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-bold text-slate-950">{item.name}</h2><Badge variant="success">{label(item.lifecycle_state)}</Badge></div><p className="mt-1 text-sm text-slate-500">{item.content_label} · active version {item.active_version || "—"}</p></div><Button variant="outline" size="sm" onClick={() => onOpenSource(item.knowledge_base_id, item.active_version_id)}><FileText className="h-4 w-4" /> View source document</Button></div>
    <div className="my-4 flex flex-wrap gap-2">{DETAIL_TABS.map((name) => <Button key={name} size="sm" variant={tab === name ? "default" : "outline"} onClick={() => setTab(name)}>{name}</Button>)}</div>
    {tab === "Overview" && <Overview item={item} />}{tab === "Rules / Concepts" && <RulesConcepts item={item} />}{tab === "Versions & Changes" && <Versions item={item} />}{tab === "Dependencies" && <section className="rounded-lg border border-slate-200 bg-white p-5"><GitBranch className="h-5 w-5 text-dq-purple" /><h3 className="mt-2 font-semibold">DSC–KB–diagnostic boundary</h3><p className="mt-2 text-sm text-slate-600">The KB supplies governed business meaning. Dataset Structure Context (DSC) supplies snapshot-specific structural evidence. Explicit local choices remain in the frozen run manifest and do not change the KB.</p></section>}{tab === "Usage & History" && <UsageHistory item={item} />}
  </div>;
}

export default function KnowledgeBasesPanel({ selectedId, onSelect, onOpenSource }) {
  const [data, setData] = useState(null); const [error, setError] = useState("");
  useEffect(() => { getKnowledgeLibraryV3().then(setData).catch((reason) => setError(reason.message)); }, []);
  if (selectedId) return <Detail knowledgeBaseId={selectedId} onBack={() => onSelect(null)} onOpenSource={onOpenSource} />;
  if (error) return <div className="rounded-md border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>;
  if (!data) return <div className="rounded-md border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500">Loading Knowledge Base Library…</div>;
  return <div className="space-y-6"><div className="grid gap-3 sm:grid-cols-4">{[["Knowledge bases", data.summary.knowledge_base_count], ["Active", data.summary.active_count], ["Working drafts", data.summary.working_draft_count], ["Proposed changes", data.summary.proposed_change_count]].map(([name, value]) => <div key={name} className="rounded-lg border border-slate-200 bg-white p-4"><div className="text-2xl font-bold text-slate-950">{value}</div><div className="mt-1 text-xs text-slate-500">{name}</div></div>)}</div><section><h2 className="mb-3 text-sm font-semibold text-slate-700">Available knowledge bases</h2><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.knowledge_bases.map((item) => <LibraryCard key={item.knowledge_base_id} item={item} onOpen={onSelect} />)}</div></section><WorkInProgress enhancements={data.upcoming_enhancements} /></div>;
}
